# Req 3: Compelling Warehouse Queries — "Predict the Future"

Same 3 queries as Part1_Group11.sql Req 3, now with actual data loaded (4 days of ETL).
Each query JOINs FactSales to all 6 Dims.

In [1]:
import pyodbc
import pandas as pd

conn = pyodbc.connect(
    r"DRIVER={ODBC Driver 17 for SQL Server};"
    r"SERVER=localhost;"
    r"DATABASE=WWI_DM;"
    r"Trusted_Connection=yes;"
)

def sql(query):
    return pd.read_sql(query, conn)

print("Connected to WWI_DM")

Connected to WWI_DM

## Query 1: Supplier Performance by City

**Business scenario:** The company wants to optimize supplier contracts by region. If Supplier A's products sell 3x more in a city than Supplier B's, we should increase Supplier A's stock in that region.

**Predict the Future:** If Supplier X dominates City Y → negotiate better terms. If a supplier is weak in a region → consider replacing.

In [4]:
# Same scenario as Part1_Group11.sql Req 3 Query 1, enhanced with ranking + revenue share
sql("""
    WITH CitySupplier AS (
        SELECT
            l.CityName, l.StateProvCode,
            s.FullName AS SupplierName, s.SupplierCategoryName,
            COUNT(DISTINCT p.ProductKey) AS Products,
            SUM(f.Quantity) AS TotalQuantity,
            SUM(f.TotalAfterTax) AS TotalRevenue
        FROM dbo.FactSales f
        JOIN dbo.DimLocation l     ON f.LocationKey    = l.LocationKey
        JOIN dbo.DimSuppliers s    ON f.SupplierKey    = s.SupplierKey
        JOIN dbo.DimCustomers c    ON f.CustomerKey    = c.CustomerKey
        JOIN dbo.DimProducts p     ON f.ProductKey     = p.ProductKey
        JOIN dbo.DimSalesPeople sp ON f.SalespersonKey = sp.SalespersonKey
        JOIN dbo.DimDate d         ON f.DateKey        = d.DateKey
        GROUP BY l.CityName, l.StateProvCode, s.FullName, s.SupplierCategoryName
    ),
    CityTotal AS (
        SELECT CityName, SUM(TotalRevenue) AS CityRevenue FROM CitySupplier GROUP BY CityName
    )
    SELECT TOP 30
        cs.CityName, cs.StateProvCode,
        cs.SupplierName, cs.SupplierCategoryName,
        cs.Products, cs.TotalQuantity, cs.TotalRevenue,
        CAST(cs.TotalRevenue * 100.0 / ct.CityRevenue AS DECIMAL(5,1)) AS RevenueSharePct,
        RANK() OVER (PARTITION BY cs.CityName ORDER BY cs.TotalRevenue DESC) AS SupplierRankInCity
    FROM CitySupplier cs
    JOIN CityTotal ct ON cs.CityName = ct.CityName
    ORDER BY ct.CityRevenue DESC, cs.TotalRevenue DESC
""")

C:\Users\blitz\AppData\Local\Temp\ipykernel_99884\4066123149.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, conn)

,CityName,StateProvCode,SupplierName,SupplierCategoryName,Products,TotalQuantity,TotalRevenue,RevenueSharePct,SupplierRankInCity
0,Jones Creek,TX,"Litware, Inc.",Packaging Supplier,5,420,10934.89,71.2,1
1,Jones Creek,TX,"Fabrikam, Inc.",Clothing Supplier,2,204,4222.80,27.5,2
2,Jones Creek,TX,Graphic Design Institute,Novelty Goods Supplier,1,7,104.65,0.7,3
3,Jones Creek,TX,The Phone Company,Novelty Goods Supplier,1,3,86.25,0.6,4
4,Lynne,FL,"Litware, Inc.",Packaging Supplier,2,324,11337.39,74.4,1
5,Lynne,FL,"Fabrikam, Inc.",Clothing Supplier,4,162,3450.00,22.6,2
6,Lynne,FL,Northwind Electric Cars,Toy Supplier,1,10,287.50,1.9,3
7,Lynne,FL,Graphic Design Institute,Novelty Goods Supplier,2,11,164.45,1.1,4
8,Marcell,MN,"Litware, Inc.",Packaging Supplier,2,170,12696.00,96.6,1
9,Marcell,MN,"Fabrikam, Inc.",Clothing Supplier,2,12,453.10,3.4,2
10,Tunnelhill,PA,"Litware, Inc.",Packaging Supplier,2,190,8602.00,67.3,1
11,Tunnelhill,PA,Northwind Electric Cars,Toy Supplier,1,6,2380.50,18.6,2
12,Tunnelhill,PA,"Fabrikam, Inc.",Clothing Supplier,1,84,1738.80,13.6,3
13,Tunnelhill,PA,Graphic Design Institute,Novelty Goods Supplier,1,4,59.80,0.5,4
14,Tomnolen,MS,"Litware, Inc.",Packaging Supplier,2,130,10292.50,80.6,1
15,Tomnolen,MS,Northwind Electric Cars,Toy Supplier,1,9,2380.50,18.6,2
16,Tomnolen,MS,"Fabrikam, Inc.",Clothing Supplier,1,3,103.50,0.8,3
17,Airport Drive,MO,"Litware, Inc.",Packaging Supplier,2,325,12691.69,99.7,1
18,Airport Drive,MO,"Fabrikam, Inc.",Clothing Supplier,1,1,36.80,0.3,2
19,Argusville,ND,"Litware, Inc.",Packaging Supplier,2,198,11327.04,95.4,1
20,Argusville,ND,"Fabrikam, Inc.",Clothing Supplier,1,7,257.60,2.2,2
21,Argusville,ND,Graphic Design Institute,Novelty Goods Supplier,1,10,149.50,1.3,3
22,Argusville,ND,Northwind Electric Cars,Toy Supplier,1,5,143.75,1.2,4
23,Golden Meadow,LA,"Litware, Inc.",Packaging Supplier,4,225,9352.38,80.6,1
24,Golden Meadow,LA,"Fabrikam, Inc.",Clothing Supplier,3,74,1757.20,15.1,2
25,Golden Meadow,LA,Graphic Design Institute,Novelty Goods Supplier,5,33,493.35,4.3,3
26,New Zion,SC,"Litware, Inc.",Packaging Supplier,2,102,6210.92,56.9,1
27,New Zion,SC,The Phone Company,Novelty Goods Supplier,1,9,2484.00,22.8,2
28,New Zion,SC,Northwind Electric Cars,Toy Supplier,1,6,1966.50,18.0,3
29,New Zion,SC,"Fabrikam, Inc.",Clothing Supplier,1,12,248.40,2.3,4

**Conclusion:**

Litware, Inc. (Packaging Supplier) ranks #1 in every city, with revenue share ranging from 56.9% (New Zion) to 99.7% (Airport Drive). This is far more than 3x Supplier B — in most cities Litware has 5-10x the revenue of the next supplier.

**Action per the scenario:**
- Increase Litware stock across all regions — they are the dominant revenue driver
- However, this extreme concentration is also a risk — if Litware has supply issues, most cities lose 70-99% of revenue
- Fabrikam (Clothing) is consistently #2 but with a huge gap — explore expanding their product range to reduce Litware dependency
- New Zion (SC) is the most diversified city (4 suppliers, #1 at 56.9%) — this is the healthiest distribution

---

## Query 2: Salesperson × Supplier Performance

**Business scenario:** Which salesperson sells which supplier's products best? By matching salespeople to the suppliers they're most effective with, we can optimize assignments and improve revenue.

**Predict the Future:**
- Salesperson X generates 80% of their revenue from Supplier A's products → assign more of that supplier's accounts to them
- Salesperson Y is weak with a key supplier → provide product training or reassign
- New supplier onboarded? → assign the salesperson who performs best with similar supplier categories

In [2]:
sql("""
    WITH SalespersonSupplier AS (
        SELECT
            sp.FullName AS SalespersonName,
            s.FullName AS SupplierName, s.SupplierCategoryName,
            COUNT(DISTINCT p.ProductKey) AS Products,
            SUM(f.Quantity) AS TotalQuantity,
            SUM(f.TotalAfterTax) AS TotalRevenue
        FROM dbo.FactSales f
        JOIN dbo.DimSalesPeople sp ON f.SalespersonKey = sp.SalespersonKey
        JOIN dbo.DimSuppliers s    ON f.SupplierKey    = s.SupplierKey
        JOIN dbo.DimProducts p     ON f.ProductKey     = p.ProductKey
        JOIN dbo.DimCustomers c    ON f.CustomerKey    = c.CustomerKey
        JOIN dbo.DimLocation l     ON f.LocationKey    = l.LocationKey
        JOIN dbo.DimDate d         ON f.DateKey        = d.DateKey
        GROUP BY sp.FullName, s.FullName, s.SupplierCategoryName
    ),
    SalespersonTotal AS (
        SELECT SalespersonName, SUM(TotalRevenue) AS SalespersonRevenue
        FROM SalespersonSupplier GROUP BY SalespersonName
    )
    SELECT TOP 30
        ss.SalespersonName, ss.SupplierName, ss.SupplierCategoryName,
        ss.Products, ss.TotalQuantity, ss.TotalRevenue,
        CAST(ss.TotalRevenue * 100.0 / st.SalespersonRevenue AS DECIMAL(5,1)) AS RevenueSharePct,
        RANK() OVER (PARTITION BY ss.SalespersonName ORDER BY ss.TotalRevenue DESC) AS SupplierRankPerSalesperson
    FROM SalespersonSupplier ss
    JOIN SalespersonTotal st ON ss.SalespersonName = st.SalespersonName
    ORDER BY st.SalespersonRevenue DESC, ss.TotalRevenue DESC
""")

C:\Users\blitz\AppData\Local\Temp\ipykernel_99884\4066123149.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, conn)

,SalespersonName,SupplierName,SupplierCategoryName,Products,TotalQuantity,TotalRevenue,RevenueSharePct,SupplierRankPerSalesperson
0,Amy Trefl,"Litware, Inc.",Packaging Supplier,17,2299,45732.92,61.8,1
1,Amy Trefl,"Fabrikam, Inc.",Clothing Supplier,22,1063,22885.00,30.9,2
2,Amy Trefl,Northwind Electric Cars,Toy Supplier,5,29,2990.00,4.0,3
3,Amy Trefl,Graphic Design Institute,Novelty Goods Supplier,9,76,1136.20,1.5,4
4,Amy Trefl,The Phone Company,Novelty Goods Supplier,4,31,1092.50,1.5,5
5,Amy Trefl,"Contoso, Ltd.",Novelty Goods Supplier,1,7,128.80,0.2,6
6,Anthony Grosse,"Litware, Inc.",Packaging Supplier,23,2903,42455.14,63.3,1
7,Anthony Grosse,"Fabrikam, Inc.",Clothing Supplier,26,853,18089.50,27.0,2
8,Anthony Grosse,Northwind Electric Cars,Toy Supplier,4,30,2932.50,4.4,3
9,Anthony Grosse,Graphic Design Institute,Novelty Goods Supplier,18,135,2018.25,3.0,4
10,Anthony Grosse,The Phone Company,Novelty Goods Supplier,6,35,1503.05,2.2,5
11,Anthony Grosse,"Contoso, Ltd.",Novelty Goods Supplier,1,4,73.60,0.1,6
12,Hudson Hollinworth,"Fabrikam, Inc.",Clothing Supplier,26,1486,29358.35,52.2,1
13,Hudson Hollinworth,"Litware, Inc.",Packaging Supplier,13,887,17951.96,31.9,2
14,Hudson Hollinworth,Northwind Electric Cars,Toy Supplier,4,32,7411.75,13.2,3
15,Hudson Hollinworth,Graphic Design Institute,Novelty Goods Supplier,11,73,1091.35,1.9,4
16,Hudson Hollinworth,The Phone Company,Novelty Goods Supplier,2,12,361.10,0.6,5
17,Hudson Hollinworth,"Contoso, Ltd.",Novelty Goods Supplier,1,4,73.60,0.1,6
18,Lily Code,"Litware, Inc.",Packaging Supplier,14,1119,24615.06,45.4,1
19,Lily Code,"Fabrikam, Inc.",Clothing Supplier,23,878,16516.30,30.5,2
20,Lily Code,Northwind Electric Cars,Toy Supplier,8,43,8314.50,15.3,3
21,Lily Code,The Phone Company,Novelty Goods Supplier,7,33,3302.80,6.1,4
22,Lily Code,Graphic Design Institute,Novelty Goods Supplier,13,99,1480.05,2.7,5
23,Jack Potter,"Litware, Inc.",Packaging Supplier,23,1957,34281.62,63.4,1
24,Jack Potter,"Fabrikam, Inc.",Clothing Supplier,19,679,13145.65,24.3,2
25,Jack Potter,Northwind Electric Cars,Toy Supplier,6,25,3547.75,6.6,3
26,Jack Potter,The Phone Company,Novelty Goods Supplier,3,11,1600.80,3.0,4
27,Jack Potter,Graphic Design Institute,Novelty Goods Supplier,16,95,1420.25,2.6,5
28,Jack Potter,"Contoso, Ltd.",Novelty Goods Supplier,1,3,55.20,0.1,6
29,Sophia Hinton,"Litware, Inc.",Packaging Supplier,17,1575,29694.10,59.3,1

**Conclusion:**

Litware (Packaging) is #1 for almost every salesperson at 59-63% revenue share — except **Hudson Hollinworth**, where Fabrikam (Clothing) leads at 52% vs Litware at 32%.

**Action per the scenario:**
- Hudson is strong with Clothing products → assign more Fabrikam/Clothing accounts to Hudson
- Amy, Anthony, Jack are Litware-dominant → deploy them in regions where Packaging push is needed
- Lily Code has 15% in Northwind (Toy Supplier), much higher than others (4-6%) → potential Toy category specialist
- Overall Litware dependency mirrors Query 1 findings → need salesperson training/incentives to grow Fabrikam and Northwind revenue

---

## Query 3: Salesperson Efficiency by Customer Category

**Business scenario:** Not all salespeople perform equally across customer types. A salesperson who excels with Corporate clients might struggle with Novelty Shops. We want to find the best match between salesperson and customer segment.

**Predict the Future:**
- Salesperson X has highest revenue/customer for "Corporate" → assign more Corporate accounts
- Salesperson Y is inefficient with "Novelty Shop" → reassign or provide training
- New customer segment growing? → assign the salesperson who performs best in similar segments

In [5]:
sql("""
    WITH SalespersonCategory AS (
        SELECT
            sp.FullName AS SalespersonName,
            c.CustomerCategoryName,
            COUNT(DISTINCT c.CustomerKey) AS UniqueCustomers,
            SUM(f.Quantity) AS TotalQuantity,
            SUM(f.TotalAfterTax) AS TotalRevenue,
            SUM(f.TotalAfterTax) / COUNT(DISTINCT c.CustomerKey) AS RevenuePerCustomer
        FROM dbo.FactSales f
        JOIN dbo.DimSalesPeople sp ON f.SalespersonKey = sp.SalespersonKey
        JOIN dbo.DimCustomers c    ON f.CustomerKey    = c.CustomerKey
        JOIN dbo.DimProducts p     ON f.ProductKey     = p.ProductKey
        JOIN dbo.DimLocation l     ON f.LocationKey    = l.LocationKey
        JOIN dbo.DimSuppliers s    ON f.SupplierKey    = s.SupplierKey
        JOIN dbo.DimDate d         ON f.DateKey        = d.DateKey
        GROUP BY sp.FullName, c.CustomerCategoryName
    ),
    CategoryTotal AS (
        SELECT CustomerCategoryName, SUM(TotalRevenue) AS CategoryRevenue
        FROM SalespersonCategory GROUP BY CustomerCategoryName
    )
    SELECT TOP 30
        sc.CustomerCategoryName, sc.SalespersonName,
        sc.UniqueCustomers, sc.TotalQuantity, sc.TotalRevenue,
        sc.RevenuePerCustomer,
        CAST(sc.TotalRevenue * 100.0 / ct.CategoryRevenue AS DECIMAL(5,1)) AS RevenueSharePct,
        RANK() OVER (PARTITION BY sc.CustomerCategoryName ORDER BY sc.TotalRevenue DESC) AS SalespersonRankInCategory
    FROM SalespersonCategory sc
    JOIN CategoryTotal ct ON sc.CustomerCategoryName = ct.CustomerCategoryName
    ORDER BY ct.CategoryRevenue DESC, sc.TotalRevenue DESC
""")

C:\Users\blitz\AppData\Local\Temp\ipykernel_99884\4066123149.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return pd.read_sql(query, conn)

,CustomerCategoryName,SalespersonName,UniqueCustomers,TotalQuantity,TotalRevenue,RevenuePerCustomer,RevenueSharePct,SalespersonRankInCategory
0,Novelty Shop,Anthony Grosse,17,3152,51558.54,3032.855294,14.6,1
1,Novelty Shop,Hudson Hollinworth,9,1536,40172.26,4463.584444,11.3,2
2,Novelty Shop,Jack Potter,16,2327,40141.10,2508.818750,11.3,3
3,Novelty Shop,Sophia Hinton,15,1585,37976.97,2531.798000,10.7,4
4,Novelty Shop,Taj Shand,20,2084,37546.13,1877.306500,10.6,5
5,Novelty Shop,Amy Trefl,12,1729,37238.15,3103.179166,10.5,6
6,Novelty Shop,Hudson Onslow,8,1082,31626.50,3953.312500,8.9,7
7,Novelty Shop,Kayla Woodcock,10,1637,27253.51,2725.351000,7.7,8
8,Novelty Shop,Archer Lamble,12,1468,25456.17,2121.347500,7.2,9
9,Novelty Shop,Lily Code,11,1076,25134.17,2284.924545,7.1,10
10,Gift Store,Lily Code,3,708,17833.74,5944.580000,26.6,1
11,Gift Store,Amy Trefl,3,583,12537.65,4179.216666,18.7,2
12,Gift Store,Jack Potter,3,262,12109.50,4036.500000,18.1,3
13,Gift Store,Taj Shand,2,131,8262.75,4131.375000,12.3,4
14,Gift Store,Anthony Grosse,2,286,6912.65,3456.325000,10.3,5
15,Gift Store,Hudson Hollinworth,2,436,6059.35,3029.675000,9.0,6
16,Gift Store,Sophia Hinton,1,264,3084.88,3084.880000,4.6,7
17,Gift Store,Archer Lamble,1,45,246.33,246.330000,0.4,8
18,Supermarket,Amy Trefl,4,688,12972.98,3243.245000,28.1,1
19,Supermarket,Kayla Woodcock,1,60,9085.00,9085.000000,19.7,2
20,Supermarket,Lily Code,3,269,8627.30,2875.766666,18.7,3
21,Supermarket,Sophia Hinton,2,337,6053.60,3026.800000,13.1,4
22,Supermarket,Hudson Hollinworth,2,274,4604.60,2302.300000,10.0,5
23,Supermarket,Hudson Onslow,2,123,2647.30,1323.650000,5.7,6
24,Supermarket,Jack Potter,1,23,1219.00,1219.000000,2.6,7
25,Supermarket,Taj Shand,2,32,916.55,458.275000,2.0,8
26,Supermarket,Anthony Grosse,1,7,104.65,104.650000,0.2,9
27,Corporate,Kayla Woodcock,2,148,11390.52,5695.260000,26.6,1
28,Corporate,Amy Trefl,2,505,11216.64,5608.320000,26.2,2
29,Corporate,Anthony Grosse,2,369,7193.25,3596.625000,16.8,3

**Conclusion:**

Novelty Shop has the largest total revenue but salesperson share is evenly spread (7-14%) — low dependency risk. Gift Store has Lily Code leading at 27%. Supermarket has Amy Trefl at 28%. Kayla Woodcock has 1 Supermarket customer generating $9,085 — highest RevenuePerCustomer overall.

**Action per the scenario:**
- Lily Code → assign more Gift Store customers (category leader at 27%)
- Amy Trefl → maintain/expand Supermarket assignment (leader at 28%)
- Kayla Woodcock → strong in both Corporate and Supermarket, candidate for high-value customer specialist
- Novelty Shop → well-distributed across salespeople, keep current assignments
- Anthony Grosse → Corporate 3rd (17%) and Novelty Shop 1st (15%) → can handle both categories